-- V31 - categorias dinâmicas, adicionais por produto e métricas diárias
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  rule text not null default 'artesanais' check (rule in ('artesanais','bebidas')),
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.categories(name,rule,sort_order,active) values
('Artesanais','artesanais',1,true),
('Combos','artesanais',2,true),
('Mistos Quentes','artesanais',3,true),
('Beach Podrão','artesanais',4,true),
('Bebidas','bebidas',5,true),
('Doces','bebidas',6,true)
on conflict (name) do nothing;

alter table public.categories enable row level security;

alter table public.products
  add column if not exists allows_addons boolean not null default false;

update public.products
set allows_addons = (category = 'Artesanais')
where allows_addons = false;

create table if not exists public.client_daily_visits (
  visit_date date not null,
  session_id text not null,
  first_seen timestamptz not null default now(),
  last_seen timestamptz not null default now(),
  primary key (visit_date, session_id)
);
create index if not exists client_daily_visits_date_idx on public.client_daily_visits(visit_date);
alter table public.client_daily_visits enable row level security;
