
-- V8.24 - Catálogo online de produtos
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  category text not null,
  name text not null,
  description text not null default '',
  price numeric(10,2) not null default 0,
  active boolean not null default true,
  available boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.products enable row level security;

-- Importa os produtos padrão somente se ainda não houver catálogo.
insert into public.products (id,category,name,description,price,active,available,sort_order)
select * from (values
(1,'Artesanais','Açu','Pão brioche, hambúrguer artesanal, queijo e salada.',15,true,true,1),
(2,'Artesanais','SJB','Pão brioche, hambúrguer artesanal, queijo, ovo e salada.',17,true,true,2),
(3,'Artesanais','Iquipari','Pão brioche, hambúrguer artesanal, queijo, ovo, calabresa e salada.',19,true,true,3),
(4,'Artesanais','Grussaí','Pão brioche, hambúrguer artesanal, queijo cheddar, ovo, bacon e salada.',21,true,true,4),
(5,'Artesanais','Chapéu do Sol','Pão brioche, hambúrguer artesanal, queijo cheddar, ovo, calabresa, bacon e salada.',23,true,true,5),
(6,'Artesanais','Balneário','Pão brioche, hambúrguer artesanal, queijo cheddar, ovo, calabresa, bacon, picles e salada.',25,true,true,6),
(7,'Artesanais','Dunas','Pão brioche, hambúrguer artesanal, queijo cheddar, frango artesanal, ovo, calabresa, bacon, picles e salada.',30,true,true,7),
(8,'Artesanais','Pontal','Pão brioche, hambúrguer artesanal, queijo cheddar, frango artesanal, 2 ovos, calabresa, bacon, picles e salada.',32,true,true,8),
(9,'Artesanais','Atafona','Pão brioche, hambúrguer artesanal, queijo cheddar, 2 frangos artesanais, 2 ovos, calabresa, bacon, picles e salada.',37,true,true,9),
(10,'Artesanais','Beach Burguer','Pão brioche, 2 hambúrgueres artesanais, 2 queijos cheddar, 2 frangos artesanais, 2 ovos, calabresa, bacon, picles e salada.',44,true,true,10),
(11,'Combos','Combo Beach Casal','2 Chapéu do Sol, 2 Guaravitas e batata 100g.',45,true,true,11),
(12,'Combos','Combo Beach Família','1 SJB, 1 Dunas, 1 Grussaí, refrigerante 1,5L e batata 200g.',67,true,true,12),
(13,'Mistos Quentes','Misto Tradicional','2 queijos, 2 presuntos, orégano, batata 100g, maionese e ketchup.',10,true,true,13),
(14,'Mistos Quentes','Misto com Ovo','2 queijos, 2 presuntos, ovo, orégano, batata 100g, maionese e ketchup.',12,true,true,14),
(15,'Mistos Quentes','Misto com Ovo e Salsicha','2 queijos, 2 presuntos, ovo, salsicha, orégano, batata 100g, maionese e ketchup.',14,true,true,15),
(16,'Beach Podrão','Beach Podrão','Pão, carne industrializada, ovo, salsicha, queijo, presunto, batata palha, milho e salada.',20,true,true,16),
(17,'Bebidas','Coca-Cola Lata','Coca-Cola lata gelada.',7,true,true,17),
(18,'Bebidas','Coca-Cola Zero Lata','Coca-Cola Zero lata gelada.',7,true,true,18),
(19,'Bebidas','Guaraná Lata','Guaraná lata gelado.',7,true,true,19),
(20,'Bebidas','Coca-Cola 1,5L','Coca-Cola 1,5 litro gelada.',12,true,true,20),
(21,'Bebidas','Coca-Cola Zero 1,5L','Coca-Cola Zero 1,5 litro gelada.',12,true,true,21),
(22,'Bebidas','Guaraná 1,5L','Guaraná 1,5 litro gelado.',12,true,true,22),
(23,'Bebidas','Guaravita','Guaravita gelado.',3,true,true,23),
(24,'Bebidas','Guaravton','Guaravton gelado.',6,true,true,24),
(25,'Bebidas','Água com gás','Água mineral com gás.',4,true,true,25),
(26,'Bebidas','Água sem gás','Água mineral sem gás.',3,true,true,26),
(27,'Bebidas','H2O','H2O gelada.',8,true,true,27)
) as v(id,category,name,description,price,active,available,sort_order)
where not exists (select 1 from public.products);

select setval(pg_get_serial_sequence('public.products','id'),
              greatest((select coalesce(max(id),1) from public.products),1), true);
