-- BEACH BURGUER PRODUÇÃO V30
-- Execute UMA VEZ no SQL Editor do Supabase ANTES de publicar a V30.

create table if not exists public.customer_addresses (
  id bigint generated by default as identity primary key,
  telefone text not null,
  address_key text not null,
  endereco text not null default '',
  numero text not null default '',
  sem_numero boolean not null default false,
  bairro text not null default '',
  referencia text not null default '',
  updated_at timestamptz not null default now(),
  unique (telefone, address_key)
);

create index if not exists customer_addresses_telefone_idx
  on public.customer_addresses(telefone);
create index if not exists customer_addresses_updated_at_idx
  on public.customer_addresses(updated_at desc);

alter table public.customer_addresses enable row level security;

-- Copia o endereço atualmente salvo em customers para o novo histórico.
insert into public.customer_addresses
  (telefone,address_key,endereco,numero,sem_numero,bairro,referencia,updated_at)
select
  telefone,
  lower(trim(regexp_replace(translate(endereco,'ÁÀÃÂÉÊÍÓÔÕÚÇáàãâéêíóôõúç','AAAAEEIOOOUCaaaaeeiooouc'),'[[:space:]]+',' ','g')))
  || '|' ||
  lower(trim(regexp_replace(translate(bairro,'ÁÀÃÂÉÊÍÓÔÕÚÇáàãâéêíóôõúç','AAAAEEIOOOUCaaaaeeiooouc'),'[[:space:]]+',' ','g'))),
  endereco,coalesce(numero,''),coalesce(sem_numero,false),bairro,coalesce(referencia,''),coalesce(updated_at,now())
from public.customers
where coalesce(telefone,'')<>'' and coalesce(endereco,'')<>'' and coalesce(bairro,'')<>''
on conflict (telefone,address_key) do update set
  numero=case when excluded.numero<>'' then excluded.numero else customer_addresses.numero end,
  sem_numero=case when excluded.numero<>'' then false else excluded.sem_numero end,
  referencia=case when excluded.referencia<>'' then excluded.referencia else customer_addresses.referencia end,
  updated_at=greatest(customer_addresses.updated_at,excluded.updated_at);
