-- Beach Burguer V31.18 - adicionais administráveis
create table if not exists public.addons (
  id bigint generated by default as identity primary key,
  name text not null unique,
  price numeric(10,2) not null default 0 check (price >= 0),
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.addons (name,price,active,sort_order) values
 ('Carne',7,true,1),('Frango',5,true,2),('Mussarela',3,true,3),('Cheddar',4,true,4),
 ('Ovo',2,true,5),('Calabresa',2,true,6),('Bacon',3,true,7),('Picles',2,true,8),('Batata',7,true,9)
on conflict (name) do nothing;

-- A API do Cloudflare usa a chave de serviço do Supabase, portanto não é necessário
-- expor escrita desta tabela diretamente ao navegador.
