-- Execute este arquivo no SQL Editor do Supabase.

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  status text not null default 'novo'
    check (status in ('novo','preparo','pronto','entregue','cancelado')),
  printed boolean not null default false,
  cliente text not null,
  telefone text not null,
  endereco text not null default '',
  bairro text not null default '',
  referencia text not null default '',
  localidade text not null default '',
  tipo text not null,
  pagamento text not null,
  troco text not null default '',
  observacoes text not null default '',
  itens jsonb not null default '[]'::jsonb,
  subtotal numeric(10,2) not null default 0,
  entrega numeric(10,2) not null default 0,
  total numeric(10,2) not null default 0
);

create index if not exists orders_created_at_idx
  on public.orders (created_at desc);

create index if not exists orders_status_idx
  on public.orders (status);

create table if not exists public.customers (
  telefone text primary key,
  nome text not null default '',
  endereco text not null default '',
  bairro text not null default '',
  referencia text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.orders enable row level security;
alter table public.customers enable row level security;

-- Nenhuma política pública é criada.
-- As Netlify Functions acessam as tabelas usando a chave secreta do servidor.
