-- Execute este arquivo no SQL Editor do Supabase.

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  status text not null default 'novo'
    check (status in ('novo','preparo','pronto','entregue','cancelado')),
  printed boolean not null default false,
  cliente text not null,
  telefone text not null,
  endereco text not null default '',
  numero text not null default '',
  sem_numero boolean not null default false,
  bairro text not null default '',
  referencia text not null default '',
  localidade text not null default '',
  tipo text not null,
  pagamento text not null,
  troco text not null default '',
  observacoes text not null default '',
  itens jsonb not null default '[]'::jsonb,
  subtotal numeric(10,2) not null default 0,
  entrega numeric(10,2) not null default 0,
  total numeric(10,2) not null default 0
);

create index if not exists orders_created_at_idx
  on public.orders (created_at desc);

create index if not exists orders_status_idx
  on public.orders (status);

create table if not exists public.customers (
  telefone text primary key,
  nome text not null default '',
  endereco text not null default '',
  numero text not null default '',
  sem_numero boolean not null default false,
  bairro text not null default '',
  referencia text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.orders enable row level security;
alter table public.customers enable row level security;

-- Nenhuma política pública é criada.
-- As Netlify Functions acessam as tabelas usando a chave secreta do servidor.


-- V5: disponibilidade online dos produtos.
create table if not exists public.product_availability (
  product_id integer primary key,
  available boolean not null default true,
  updated_at timestamptz not null default now()
);

insert into public.product_availability (product_id, available)
select id, true
from generate_series(1, 27) as id
on conflict (product_id) do nothing;

alter table public.product_availability enable row level security;


-- BEACH BURGUER V8.6 — PIX AUTOMÁTICO MERCADO PAGO
-- Execute UMA VEZ no SQL Editor do Supabase.

alter table public.orders
  add column if not exists pix_payment_id text,
  add column if not exists pix_status text;

create unique index if not exists orders_pix_payment_id_unique
  on public.orders (pix_payment_id)
  where pix_payment_id is not null;

create table if not exists public.pix_payments (
  payment_id text primary key,
  external_reference text not null default '',
  status text not null default 'pending',
  amount numeric(10,2) not null default 0,
  payer_email text not null default '',
  qr_code text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists pix_payments_status_idx
  on public.pix_payments (status);

alter table public.pix_payments enable row level security;



-- V8.24 - Catálogo online de produtos
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  category text not null,
  name text not null,
  description text not null default '',
  price numeric(10,2) not null default 0,
  active boolean not null default true,
  available boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.products enable row level security;

-- Importa os produtos padrão somente se ainda não houver catálogo.
insert into public.products (id,category,name,description,price,active,available,sort_order)
select * from (values
(1,'Artesanais','Açu','Pão brioche, hambúrguer artesanal, queijo e salada.',15,true,true,1),
(2,'Artesanais','SJB','Pão brioche, hambúrguer artesanal, queijo, ovo e salada.',17,true,true,2),
(3,'Artesanais','Iquipari','Pão brioche, hambúrguer artesanal, queijo, ovo, calabresa e salada.',19,true,true,3),
(4,'Artesanais','Grussaí','Pão brioche, hambúrguer artesanal, queijo cheddar, ovo, bacon e salada.',21,true,true,4),
(5,'Artesanais','Chapéu do Sol','Pão brioche, hambúrguer artesanal, queijo cheddar, ovo, calabresa, bacon e salada.',23,true,true,5),
(6,'Artesanais','Balneário','Pão brioche, hambúrguer artesanal, queijo cheddar, ovo, calabresa, bacon, picles e salada.',25,true,true,6),
(7,'Artesanais','Dunas','Pão brioche, hambúrguer artesanal, queijo cheddar, frango artesanal, ovo, calabresa, bacon, picles e salada.',30,true,true,7),
(8,'Artesanais','Pontal','Pão brioche, hambúrguer artesanal, queijo cheddar, frango artesanal, 2 ovos, calabresa, bacon, picles e salada.',32,true,true,8),
(9,'Artesanais','Atafona','Pão brioche, hambúrguer artesanal, queijo cheddar, 2 frangos artesanais, 2 ovos, calabresa, bacon, picles e salada.',37,true,true,9),
(10,'Artesanais','Beach Burguer','Pão brioche, 2 hambúrgueres artesanais, 2 queijos cheddar, 2 frangos artesanais, 2 ovos, calabresa, bacon, picles e salada.',44,true,true,10),
(11,'Combos','Combo Beach Casal','2 Chapéu do Sol, 2 Guaravitas e batata 100g.',45,true,true,11),
(12,'Combos','Combo Beach Família','1 SJB, 1 Dunas, 1 Grussaí, refrigerante 1,5L e batata 200g.',67,true,true,12),
(13,'Mistos Quentes','Misto Tradicional','2 queijos, 2 presuntos, orégano, batata 100g, maionese e ketchup.',10,true,true,13),
(14,'Mistos Quentes','Misto com Ovo','2 queijos, 2 presuntos, ovo, orégano, batata 100g, maionese e ketchup.',12,true,true,14),
(15,'Mistos Quentes','Misto com Ovo e Salsicha','2 queijos, 2 presuntos, ovo, salsicha, orégano, batata 100g, maionese e ketchup.',14,true,true,15),
(16,'Beach Podrão','Beach Podrão','Pão, carne industrializada, ovo, salsicha, queijo, presunto, batata palha, milho e salada.',20,true,true,16),
(17,'Bebidas','Coca-Cola Lata','Coca-Cola lata gelada.',7,true,true,17),
(18,'Bebidas','Coca-Cola Zero Lata','Coca-Cola Zero lata gelada.',7,true,true,18),
(19,'Bebidas','Guaraná Lata','Guaraná lata gelado.',7,true,true,19),
(20,'Bebidas','Coca-Cola 1,5L','Coca-Cola 1,5 litro gelada.',12,true,true,20),
(21,'Bebidas','Coca-Cola Zero 1,5L','Coca-Cola Zero 1,5 litro gelada.',12,true,true,21),
(22,'Bebidas','Guaraná 1,5L','Guaraná 1,5 litro gelado.',12,true,true,22),
(23,'Bebidas','Guaravita','Guaravita gelado.',3,true,true,23),
(24,'Bebidas','Guaravton','Guaravton gelado.',6,true,true,24),
(25,'Bebidas','Água com gás','Água mineral com gás.',4,true,true,25),
(26,'Bebidas','Água sem gás','Água mineral sem gás.',3,true,true,26),
(27,'Bebidas','H2O','H2O gelada.',8,true,true,27)
) as v(id,category,name,description,price,active,available,sort_order)
where not exists (select 1 from public.products);

select setval(pg_get_serial_sequence('public.products','id'),
              greatest((select coalesce(max(id),1) from public.products),1), true);



-- BEACH BURGUER V8.30
-- Execute UMA VEZ no SQL Editor do Supabase.
alter table public.orders
  add column if not exists origem text not null default 'cliente';

-- Pedidos antigos permanecem como cliente.
update public.orders
set origem = 'cliente'
where origem is null or origem = '';


-- V25: presença aproximada de clientes online
create table if not exists public.client_presence (
  session_id text primary key,
  last_seen timestamptz not null default now()
);
create index if not exists client_presence_last_seen_idx on public.client_presence(last_seen);
alter table public.client_presence enable row level security;
