const $=id=>document.getElementById(id), TK='bb_store_token'; let token=localStorage.getItem(TK)||''; const moeda=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}); const hoje=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo'}).format(new Date());
$('data').value=hoje(); $('senha').value=token;
async function api(body){const r=await fetch('/api/finance',{method:'POST',headers:{'Content-Type':'application/json','X-Store-Token':token},body:JSON.stringify(body)});const d=await r.json();if(!r.ok||!d.ok)throw Error(d.error||'Erro');return d}
async function entrar(){token=$('senha').value.trim();try{await api({action:'summary',date:$('data').value});localStorage.setItem(TK,token);$('login').classList.add('hidden');$('app').classList.remove('hidden');carregar()}catch(e){alert('Senha inválida ou banco ainda não preparado.')}}
$('entrar').onclick=entrar;$('senha').onkeydown=e=>{if(e.key==='Enter')entrar()};$('sair').onclick=()=>{localStorage.removeItem(TK);location.reload()};$('atualizar').onclick=carregar;
async function carregar(){try{const d=await api({action:'summary',date:$('data').value});const t=d.closing?{Dinheiro:Number(d.closing.cash_total||0),'Cartão':Number(d.closing.card_total||0),Pix:Number(d.closing.pix_total||0)}:d.sales.totals;$('dinheiro').textContent=moeda(t.Dinheiro);$('cartao').textContent=moeda(t['Cartão']);$('pix').textContent=moeda(t.Pix);$('total').textContent=moeda(t.Dinheiro+t['Cartão']+t.Pix);$('pendente').value=d.closing?.pending_unclassified??'';$('receberDinheiro').value='';$('receberCartao').value='';renderContas(d.accounts);renderLivro(d.ledger)}catch(e){alert(e.message)}}
$('salvarFechamento').onclick=async()=>{try{const d=await api({action:'save_closing',date:$('data').value,pending_unclassified:$('pendente').value,received_cash:$('receberDinheiro').value,received_card:$('receberCartao').value});alert(d.received_total>0?`Fechamento salvo. ${moeda(d.received_total)} recebido do A pagar e lançado no Livro Caixa.`:'Fechamento salvo.');carregar()}catch(e){alert(e.message)}};
$('criarConta').onclick=async()=>{try{const d=await api({action:'create_account',description:$('contaDesc').value,due_date:$('contaVenc').value,amount_due:$('contaValor').value});$('contaDesc').value='';$('contaValor').value='';alert(d.carried>0?`Conta criada. Saldo anterior de ${moeda(d.carried)} foi somado.`:'Conta criada.');carregar()}catch(e){alert(e.message)}};
$('addLanc').onclick=async()=>{try{await api({action:'add_ledger',date:$('data').value,type:$('lancTipo').value,description:$('lancDesc').value,amount:$('lancValor').value});$('lancDesc').value='';$('lancValor').value='';carregar()}catch(e){alert(e.message)}};
function renderContas(list){$('contas').innerHTML=(list||[]).map(a=>`<div class="account"><div style="display:flex;justify-content:space-between;gap:8px"><strong>${esc(a.description)}</strong><span class="pill">${esc(a.status)}</span></div><div class="muted">Venc.: ${a.due_date||'-'} • Valor a pagar: ${moeda(a.amount_due)} • Pago: ${moeda(a.amount_paid)} • <strong>Restante: ${moeda(a.remaining)}</strong></div>${a.status!=='quitada'?`<div style="display:flex;gap:7px;margin-top:8px"><input id="pay${a.id}" type="number" step="0.01" placeholder="Valor pago"><button class="btn green" onclick="pagar(${a.id})">Registrar pagamento</button></div>`:''}</div>`).join('')||'<p class="muted">Nenhuma conta cadastrada.</p>'}
window.pagar=async id=>{const el=$('pay'+id);try{await api({action:'pay_account',id,amount_paid:el.value,date:$('data').value});carregar()}catch(e){alert(e.message)}};
function renderLivro(list){$('livro').innerHTML=(list||[]).map(x=>`<div><span>${esc(x.description)}<br><small class="muted">${esc(x.source||'')}</small></span><strong class="${x.type}">${x.type==='saida'?'-':'+'} ${moeda(x.amount)}</strong></div>`).join('')||'<p class="muted">Sem lançamentos nesta data.</p>'}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
if(token)entrar();
