-- V31.94 - Sorteio de cupons: configuração, geração, cancelamento e sorteio seguro
create table if not exists public.raffle_settings (
  id bigint primary key default 1 check (id=1),
  enabled boolean not null default false,
  purchase_amount numeric(10,2) not null default 25.00 check (purchase_amount > 0),
  updated_at timestamptz not null default now()
);
insert into public.raffle_settings(id,enabled,purchase_amount)
values(1,false,25.00)
on conflict (id) do nothing;

create table if not exists public.raffle_coupons (
  id bigint generated by default as identity primary key,
  order_id bigint not null,
  coupon_number integer not null unique check (coupon_number between 100000 and 999999),
  customer_name text not null,
  phone text not null default '',
  origin text not null default 'cliente',
  purchase_total numeric(10,2) not null default 0,
  status text not null default 'valid' check (status in ('valid','cancelled','drawn')),
  created_at timestamptz not null default now(),
  cancelled_at timestamptz,
  drawn_at timestamptz
);
create index if not exists raffle_coupons_order_idx on public.raffle_coupons(order_id);
create index if not exists raffle_coupons_draw_idx on public.raffle_coupons(status,drawn_at,created_at);

create table if not exists public.raffle_draws (
  id bigint generated by default as identity primary key,
  coupon_id bigint not null references public.raffle_coupons(id),
  coupon_number integer not null,
  customer_name text not null,
  phone text not null default '',
  order_id bigint not null,
  drawn_at timestamptz not null default now()
);
create index if not exists raffle_draws_date_idx on public.raffle_draws(drawn_at desc);

-- Gera a quantidade de cupons automaticamente na criação do pedido.
-- O número é aleatório e a UNIQUE constraint garante que nunca seja repetido.
create or replace function public.generate_raffle_coupons_for_order()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
declare
  cfg public.raffle_settings%rowtype;
  qty integer;
  i integer;
  new_number integer;
  inserted_id bigint;
  tries integer;
begin
  select * into cfg from public.raffle_settings where id=1;
  if not coalesce(cfg.enabled,false) or coalesce(cfg.purchase_amount,0)<=0 then
    return new;
  end if;

  qty=floor(coalesce(new.total,0)/cfg.purchase_amount)::integer;
  if qty<=0 then return new; end if;

  for i in 1..qty loop
    tries=0;
    loop
      tries=tries+1;
      if tries>100 then raise exception 'Não foi possível gerar um número único de cupom.'; end if;
      new_number=floor(random()*900000)::integer+100000;
      insert into public.raffle_coupons(order_id,coupon_number,customer_name,phone,origin,purchase_total)
      values(new.id,new_number,coalesce(new.cliente,'Cliente'),coalesce(new.telefone,''),coalesce(new.origem,'cliente'),coalesce(new.total,0))
      on conflict (coupon_number) do nothing
      returning id into inserted_id;
      exit when inserted_id is not null;
    end loop;
  end loop;
  return new;
end;
$$;

drop trigger if exists trg_generate_raffle_coupons on public.orders;
create trigger trg_generate_raffle_coupons
after insert on public.orders
for each row execute function public.generate_raffle_coupons_for_order();

-- Se um pedido for cancelado/removido, seus cupons deixam de participar.
create or replace function public.cancel_raffle_coupons_for_order()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
begin
  update public.raffle_coupons
     set status='cancelled', cancelled_at=coalesce(cancelled_at,now())
   where order_id=old.id and status='valid';
  return old;
end;
$$;
drop trigger if exists trg_cancel_raffle_coupons on public.orders;
create trigger trg_cancel_raffle_coupons
before delete on public.orders
for each row execute function public.cancel_raffle_coupons_for_order();

-- Edição de pedido do Garçom: invalida os cupons anteriores e gera novamente
-- de acordo com o novo valor/nome/telefone.
create or replace function public.refresh_raffle_coupons_after_order_update()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
declare
  cfg public.raffle_settings%rowtype;
  qty integer;
  i integer;
  new_number integer;
  inserted_id bigint;
  tries integer;
begin
  if new.origem <> 'garcom' then return new; end if;
  if coalesce(old.total,0)=coalesce(new.total,0)
     and coalesce(old.cliente,'')=coalesce(new.cliente,'')
     and coalesce(old.telefone,'')=coalesce(new.telefone,'') then
    return new;
  end if;

  update public.raffle_coupons
     set status='cancelled', cancelled_at=coalesce(cancelled_at,now())
   where order_id=new.id and status='valid';

  select * into cfg from public.raffle_settings where id=1;
  if not coalesce(cfg.enabled,false) or coalesce(cfg.purchase_amount,0)<=0 then return new; end if;
  qty=floor(coalesce(new.total,0)/cfg.purchase_amount)::integer;
  if qty<=0 then return new; end if;

  for i in 1..qty loop
    tries=0;
    loop
      tries=tries+1;
      if tries>100 then raise exception 'Não foi possível gerar um número único de cupom.'; end if;
      new_number=floor(random()*900000)::integer+100000;
      insert into public.raffle_coupons(order_id,coupon_number,customer_name,phone,origin,purchase_total)
      values(new.id,new_number,coalesce(new.cliente,'Cliente'),coalesce(new.telefone,''),coalesce(new.origem,'garcom'),coalesce(new.total,0))
      on conflict (coupon_number) do nothing
      returning id into inserted_id;
      exit when inserted_id is not null;
    end loop;
  end loop;
  return new;
end;
$$;
drop trigger if exists trg_refresh_raffle_coupons on public.orders;
create trigger trg_refresh_raffle_coupons
after update of total,cliente,telefone on public.orders
for each row execute function public.refresh_raffle_coupons_after_order_update();

-- Sorteio atômico no servidor. Só cupons válidos entram e cada cupom pode ser sorteado uma vez.
create or replace function public.draw_raffle_coupon()
returns table(coupon_id bigint,coupon_number integer,customer_name text,phone text,order_id bigint,drawn_at timestamptz)
language plpgsql
security definer
set search_path=public
as $$
declare
  c public.raffle_coupons%rowtype;
begin
  select * into c
    from public.raffle_coupons
   where status='valid' and drawn_at is null
   order by random()
   for update skip locked
   limit 1;
  if c.id is null then
    return;
  end if;
  update public.raffle_coupons
     set status='drawn', drawn_at=now()
   where id=c.id;
  insert into public.raffle_draws(coupon_id,coupon_number,customer_name,phone,order_id)
  values(c.id,c.coupon_number,c.customer_name,c.phone,c.order_id);
  return query select c.id,c.coupon_number,c.customer_name,c.phone,c.order_id,now();
end;
$$;
