BEGIN;

CREATE TABLE IF NOT EXISTS public.delivery_blocked_zones (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL DEFAULT 'Área sem entrega',
  locality text NOT NULL,
  polygon jsonb NOT NULL DEFAULT '[]'::jsonb,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.delivery_blocked_zones ENABLE ROW LEVEL SECURITY;

COMMIT;
