-- V31.80 - Endereços sem entrega (backend-only)
create table if not exists public.blocked_addresses (
  id bigint generated by default as identity primary key,
  street text not null,
  number text not null,
  reference text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.blocked_addresses enable row level security;
-- Sem policies: Cliente/Admin acessam exclusivamente pela API backend (service_role).
