-- V31.68 - fila exclusiva para testes de impressora. Não usa public.orders.
create table if not exists public.printer_jobs (
  id bigint generated by default as identity primary key,
  kind text not null default 'test',
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  printed_at timestamptz
);
create index if not exists printer_jobs_pending_idx on public.printer_jobs(status, created_at);
