-- V31.34 - Livro Caixa, Contas a Pagar e Fechamento de Caixa
create table if not exists public.cash_closings (
  id bigint generated by default as identity primary key,
  closing_date date not null unique,
  cash_total numeric(12,2) not null default 0,
  card_total numeric(12,2) not null default 0,
  pix_total numeric(12,2) not null default 0,
  pending_unclassified numeric(12,2) not null default 0,
  notes text not null default '',
  updated_at timestamptz not null default now()
);
create table if not exists public.accounts_payable (
  id bigint generated by default as identity primary key,
  description text not null,
  due_date date,
  base_amount numeric(12,2) not null default 0,
  carried_amount numeric(12,2) not null default 0,
  amount_due numeric(12,2) not null default 0,
  amount_paid numeric(12,2) not null default 0,
  remaining numeric(12,2) not null default 0,
  status text not null default 'pendente',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.cash_ledger (
  id bigint generated by default as identity primary key,
  entry_date date not null,
  type text not null check (type in ('entrada','saida')),
  description text not null,
  amount numeric(12,2) not null default 0,
  source text not null default 'manual',
  account_id bigint references public.accounts_payable(id) on delete set null,
  created_at timestamptz not null default now()
);
create index if not exists cash_ledger_entry_date_idx on public.cash_ledger(entry_date);
create index if not exists accounts_payable_status_idx on public.accounts_payable(status);
