-- Beach Burguer V31.54
-- Cadastro separado de adicionais obrigatorios.

create table if not exists public.required_addons (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric(10,2) not null default 0,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.products
  add column if not exists required_addon boolean not null default false;

comment on table public.required_addons is 'Lista separada dos adicionais comuns. Usada apenas em produtos marcados com Adicional obrigatorio.';
comment on column public.products.required_addon is 'Quando true, Cliente e Garcom exigem uma escolha da lista public.required_addons.';
